# Date: March 7th, 2022
# Author: Brendan Keane
# Purpose: Report tab for this user interface

# Libraries
library("shiny")

# Report tab
report_tab <- tabPanel(
  "Report",
  h1("Exploring the Relationship Between COVID-19 and Dietary Health"),
  p("Author: Brendan Keane, Sean Lim, Jessy Irvine, Jerry Zhang, Yonas Mekonnen"),
  p("Affiliation: INFO-201: Technical Foundations of Informatics - The Information School - University of Washington"),
  p("Date:February 18th, 2022"),
  p(""),
  h3("Abstract"),
  p("This project uses global food and COVID-19 data to explore the relationship between diet and COVID-19 mortality. Correlations between these two factors could indicate that (1) healthy diets improve COVID-19 outcomes, (2) countries with enough food are better equipped to combat COVID, or (3) a combination of both."),
  h3("Introduction"),
  p("Over the last two years, the COVID-19 pandemic has swept across world. During this time, scientists, politicians, and world leaders have been trying to find a way to return to normal. By finding correlations between dietary data and COVID-19 statistics, we hope to gain valuable information on how diet effects COVID-19 mortality. More specifically, we will explore correlations between COVID-19 mortality and nations macronutrient consumption through the COVID-19 Healthy Diet Dataset. By understanding these data, we can better understand dietary health’s relationship with our immune systems. "),
  h3("Design situation"),
  p("Before vaccines were widely accessible in the United States, scientists looked to diet as a method to combat COVID-19. Researchers used COVID-19 mortality in conjunction with food data to find a correlation between country’s diet and COVID-19 mortality rate. While much of this research suggests that “a plant based rich fiber diet… appears to be advantageous” some researchers argue that countries mortality data cannot be compared because of various collection biases. While these data collection biases are of concern, “obesity, a risk factor of mortality in COVID-19, suggests the importance of nutrition” . For this reason, we will investigate diet and COVID-19 by isolating specific food habits and comparing them with COVID-19 mortality. These data are connected to international life and health. Every number in this dataset tells a story of public health, agriculture, supply chains, and the industrialization of food. Although each community has a unique cultural relationship with food, all humans require proper nutrition to meet their health needs. When food is commodified, these health needs are compromised in favor of cost, convenience, and accessibility. We acknowledge that dietary choice is a privilege and that the findings of this research are a reflection of systemic issues with dietary health. This project consists of governments, farmers, and supply chain managers as direct stakeholders as their actions directly impact the quantity and quality of food distributed to people. Governments are motivated to support population health in order to maintain societal function. Farms and supply chain managers are motivated to allocate food throughout their respective areas. Additionally healthcare workers, schools, high-risk individuals, and all humans are indirect stakeholders as their health and safety are impacted by the direct stakeholders. Analyzing COVID-19 data at a global scale is challenging as “most diseases exhibit large geographical variations which frequently remain unexplained despite abundant research”. Reactive adoption of diet is not uncommon and “such diets in the long term are unsustainable and can bring adverse side effects to health” . However, diet-based issues like obesity have been acknowledged as a “public health threat, with the government failing to reverse this growing trend”. Governments, farmers, supply chain managers, and concerned citizens should use this research to structure and support food initiatives that improve population health. "),
  h3("Research questions"),
  p("Is there a relationship between diet and COVID-19 mortality?
Does a conventionally healthy diet (low sugar, low sodium, low fat, high produce) strengthen the immune system, reducing COVID-19 mortality?
Does a high quantity of processed food relate to high COVID-19 mortality? "),
  h3("Dataset"),
  p("This data set, Food Supply Kcal, represents the global population affected by COVID-19. With this, the data set also accounts for the food supply, nutrition values, obesity percentages, malnourishment percentages, and food habits of the countries represented. Among these broad categories the data set exhibits, variables such as COVID-19 deaths, active cases, and recovery cases are also analyzed. Having these variables allows the correlation between global food habits, and global COVID-19 cases more easily understandable, and also puts the correlation into perspective for the audience of the data. The set excludes the variables race and gender. While excluding these do not change the validity of the data, nor do they compromise the purpose, adding variables such as race and gender, could illustrate any disproportionate infection rates based on these two factors, and if they are affected by different diets. This could also show any commonalities between men’s and women’s diets and which gender tends to have a higher infection rate. The data was amassed by Kaggle user Marila Prata, who collected information from sources like, the Food and Agriculture Organization of The United Nations , the Population Reference Bureau  , the Johns Hopkins Center for Systems Science and Engineering  , and the USDA center for Nutrition. The data was originally collected in the beginning of the COVID-19 pandemic and has been updated since, yet ceased updates in April of 2020. Collecting this data was an attempt at answering the question: what non-pharmaceutical interventions could the population make in order to stop the spread of COVID-19? No funding was involved to collect the data, as the majority of the information is publicly available. Alternatively, those who could benefit, or financially benefit from a data set of this nature would be direct stakeholders such as large healthcare organizations and the government, specifically food and agricultural divisions. The validity of this data is strong. Many of the resources cited come from official United States government websites, and a reputable source, John Hopkins. Besides COVID-19 information collected from Johns Hopkins, there was no data included in the set from a source outside of official, public information. This makes the data easier to trust as it is assumed information that originates from the United States government is honest, and not exclusionary. This data was obtained from Kaggle, an online platform used to publish and find datasets. The source of the data is credited as kaggle, and the aforementioned sources are factual and verifiable. "),
  h3("Findings"),
  p("That correlation I talked about only holds up in the most populated countries. When I graph obesity and covid mortality rate, mortality gets progressively worse from 0-15% obesity, and then it gets better when above 15% obesity. I believe this indicates that nations that can overfeed their population are likely to have access to better healthcare resources.
I also noticed that Cereal has the strongest correlation with an increased covid mortality rate. This would be supported by some Indian studies that say processed food correlates with worse gut health, and subsequently a worse immune system.
High amounts of vegetable products results in a higher mortality rate, high amounts of animal products results in lower mortality rate. This contradicts the research around gut health which claims that plant-based diets cultivate better gut health and therefore a better immune response. However, as with the obesity rate research, having access to animal products is more common in more developed nations."),
  h3("Discussion"),
  p("First of all, according to the graph I found that the number of Covid-19 deaths and the number of cases are increasing proportionally, for some countries, such as Vanuatu, he counts very few deaths, and for example, the United States, his number of deaths and cases are counted The highest number of Covid-19 cases, 77,918,466 cases and 922,470 deaths. But this does not mean that the United States is the country with the highest number of deaths in the number of cases. According to the chart , we can explore that the country with the highest death rate is Yemen, whose number of cases is only 11,679.
, but his death toll reached an astonishing 2,107, almost 1/5 of the death rate. So in order to explore the relationship between the severity of COVID and the nutritional ratio of food, we compared the nutritional status of yemen with a country with a normal mortality rate (the United States), and we found that almost all of yemen's Egg, Seafood, Meat and vegetable are less 1/2 of the nutrient ratio of American food. The bigger difference is milk. The milk content in the United States is almost 10 times that of yemen. As a result, we can find that countries with high and balanced food nutrition ratios have lower mortality rates. In addition to this, we also wanted to explore the relationship between alcoholic beverages and mortality, and we found that countries with lower COVID fatality rates had a slightly larger share of alcoholic beverages, and countries with higher fatality rates had a slightly smaller share of alcoholic beverages. Combining the answers to the research question in the finding above, the obesity rates for each country were In conclusion, we found that countries that are able to overfeed their populations may have better access to medical resources. This proves that the country's COVID-19 profile can also be predicted based on the country's obesity rate. In addition, there is also a strong relationship between obesity rate and food and nutrition supply. Therefore, in order to improve the situation of COVID-19 in the country, the country should pay more attention to the issue of balanced food supply and nutrition. situation is very important. In addition, it is extremely important to find the conclusion that cereals have the strongest correlation with the increased mortality of the new coronavirus, because it is directly related to the mortality of COVID. Increasing the ratio of food nutrients that are helpful for intestinal absorption plays a crucial role in reducing the mortality rate of COVID19. Finally, countries with a high dietary intake of animal products have lower mortality rates than countries with a high dietary intake of plant products, and according to the study, a plant-based diet can foster better gut health and thus better immunity reaction. According to this result, it can be inferred that the mortality rate is not strongly related to the level of animal products and plant products. The stronger relationship is because the countries with high animal products are generally more developed and have stronger medical security measures."),
  h3("Conclusion"),
  p("To sum up, countries with higher obesity rates and higher animal food products are generally more developed and therefore have higher levels of medical care to combat the new coronavirus. In addition, studies have shown that cereal products are directly related to mortality, so during COVID, you should pay more attention to eating foods that are easily absorbed by the intestines to increase immunity to resist the new crown.")
  )
